# Generated by Django 4.1 on 2022-08-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='static/auctions')),
                ('description', models.CharField(max_length=100)),
                ('bid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Antiques', 'Antiques'), ('Electronics', 'Electronics'), ('Machinery', 'Machinery'), ('Fashion', 'Fashion'), ('Home', 'Home'), ('Sports', 'Sports'), ('Retail', 'Retail'), ('Toys', 'Toys'), ('Tools', 'Tools'), ('Vehicles', 'Vehicles'), ('Recreation', 'Recreation')], default='Antiques', max_length=11)),
            ],
        ),
    ]
