# Generated by Django 4.1 on 2022-09-09 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_listing_bid_alter_bid_auction_alter_bid_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='Bid',
        ),
        migrations.AlterField(
            model_name='bid',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listing', to='auctions.listing'),
        ),
    ]
