# Generated by Django 4.1 on 2022-09-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_listing_bid_alter_bid_auction'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='bidNumber',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='watchlist',
            field=models.BooleanField(default=False),
        ),
    ]
