# Generated by Django 4.1 on 2022-09-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_bid_listing_bidnumber_listing_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bidNumber',
            field=models.FloatField(default=0),
        ),
    ]
