# Generated by Django 4.1 on 2022-09-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listing_bidnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bidNumber',
            field=models.IntegerField(default=0),
        ),
    ]
