# Generated by Django 4.1 on 2022-09-09 20:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_listing_bidnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='watchlist',
        ),
        migrations.AddField(
            model_name='listing',
            name='watching',
            field=models.ManyToManyField(related_name='watchers', to=settings.AUTH_USER_MODEL),
        ),
    ]
